### PR TITLE
feat: use logger instead of console.log

### PR DESCRIPTION
**Pull request by ledleds**
This PR relates to Issue #4 
- Replace the use of console.log with core logger
- Add an error log

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by dkundel** [comment]
Thank you for your contribution @ledleds! Unfortunately GitHub Actions at the moment requires `node_modules` to be present in the repository as [described in the docs](https://help.github.com/en/articles/creating-a-javascript-action#commit-and-push-your-action-to-github). 

We should ultimately switch over to bundling the dependencies but that will require us to bundle all relevant licenses as well. So it's currently pushed out. 

Could you revert the `.gitignore` changes and I'm happy to merge your PR.

**Comment by ledleds** [comment]
Ah damn, OK will revert!

**Comment by dkundel** [comment]
@ledleds we want to say thank you for you contributing to this project and send you some swag after Hacktoberfest. All you have to do is fill out this form: https://twil.io/hacktoberfest-swag

**Comment by ledleds** [comment]
Awesome. Thanks!

**Pull request merged**
